### PR TITLE
[YearSelection] Do not call shouldDisableDate on year selection view for each year

### LINKED ISSUE #1774: Last year is not clickable when use minDate and maxDate
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     4.0.0-alpha.7    |
| material-ui          |    4.9.10     |
| TypeScript           |         |
| React                |     16.13.1    |
| Browser              |         |
| Peer library         |    date-fns     |  |

## Steps to reproduce

Same code as mentioned in https://v4-0-0-alpha-7.material-ui-pickers.dev/demo/datepicker
  ```
     <DesktopDatePicker
        autoOk
        label="For desktop"
        renderInput={props => <TextField {...props} />}
        minDate={new Date("2017-06-06")}
        maxDate={new Date("2100-12-31")}
        value={selectedDate}
        onChange={date => handleDateChange(date)}
      />
```

When the minDate (2017-06-06) month is not starting Month i.e Jan, then when you click last year that is 2100, is not clickable
Screen Shot 2020-05-15 at 2 02 14 AM
## Expected behavior
If minDate does not have starting Month i.e. Jan then also last year should be clickable

## Actual behavior
Last Year 2100 is not clickable

**Can anyone provide the workaround or If possible can it be fix as hot-fix.** Thanks!

### LINKED ISSUE #1899: Year selector calling "shouldDisableDate"
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    v4-0-0-alpha-8     |
| material-ui          |    ^4.10.1     |
| TypeScript           |   ^3.8.3      |
| React                |    "^16.13.1"     |
| Browser              |     any    |
| Peer library         |    date-fns     |  |

## Steps to reproduce

1. 2. 3.
1. Create a custom function to disable weekends, for example
```
  function shouldDisableDate(day, pickerProps) {
    return day.getDay() === 0 || day.getDay() === 6;
  }

```
And call it in any datepicker.

This function is being called at the year selector, disabling years that should not be disabled

image

## Expected behavior

Year selector screen should only call shouldDisableYear right?

## Actual behavior

image

https://codesandbox.io/s/cranky-black-iuqu4?file=/src/App.jsx:263-368

Couldn't get it running, but you can see the code

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).

Closes #1899. 

Also closes #1774, because we are looking for closest enabled date if the "shifted" date is disabled now.

### CODE REVIEW

File: lib/src/views/Calendar/YearSelection.tsx [hunk 1]
```diff
@@ -70,6 +73,21 @@ export const YearSelection: React.FC<YearSelectionProps> = ({
...
+          maxDate,
+          disablePast: Boolean(disablePast),
+          disableFuture: Boolean(disableFuture),
+          shouldDisableDate: isDateDisabled,
+        });
+
+        onChange(closestEnabledDate, isFinish);
+        if (onYearChange) {
+          onYearChange(newDate);
+        }
```
Comment (oliviertassinari) [inline lib/src/views/Calendar/YearSelection.tsx]: The call order between onChange and onYearChange isn't stable. Should be we care about it?

**Review by oliviertassinari — APPROVED** [review]

File: lib/src/views/Calendar/YearSelection.tsx (hunk 1 above)
Comment (dmtrKovalenko) [reply lib/src/views/Calendar/YearSelection.tsx]: Fixed
