### PR TITLE
[DatePicker] add strictCompareDates prop

### LINKED ISSUE #953: minDate and maxDate range on the DateTimePicker
DepbmEA

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.2.4      |
| material-ui         |     3.9.2    |
| React               |      16.8.4   |
| Browser             |  chrome       |
| Peer library        |  moment       | 

## Expected behavior
minDate and maxDate should invalidate if a date is one second apart on the DateTimePicker

## Actual behavior
minDate and maxDate do not work as exepected on the DateTimePicker.
It only invalidates if the current date is a day after the maxDate or the current date is a day before the minDate.

## Live example

   [LIVE EXAMPLE]( https://codesandbox.io/s/8ly830zw5j?fontsize=14)

### PR DESCRIPTION
**Pull request by sviande**
Add strict camparison for minDate, maxDate, disablePast, disableFuture

This PR closes #953 

## Description
Add property to force strict comparison on minDate, maxDate, disablePast and disableFuture
Exemple: without validateStrict no maxDateMessage is shown
```
  return (
      <>
          <KeyboardDateTimePicker
              label="Wiil nopt show max date message"
              value={new Date('2019-05-28T23:00:00.000Z')}
              maxDate={new Date('2019-05-28T00:00:00.000Z')}
          />
          <KeyboardDateTimePicker
              label="Will show max date message"
              validateStrict
              value={new Date('2019-05-28T23:00:00.000Z')}
              maxDate={new Date('2019-05-28T00:00:00.000Z')}
          />
      </>
  );
```

### CODE REVIEW

File: lib/src/_helpers/text-field-helper.ts [hunk 1]
```diff
@@ -69,15 +86,25 @@ export const validate = (
   }
 
   if (
-    (maxDate && utils.isAfter(parsedValue, utils.endOfDay(utils.date(maxDate)))) ||
-    (disableFuture && utils.isAfter(parsedValue, utils.endOfDay(utils.date())))
+    (maxDate &&
```
Comment (dmtrKovalenko) [inline lib/src/_helpers/text-field-helper.ts]: Ohh god this code looks spaghetti. It must be refactored

File: lib/src/DatePicker/DatePicker.tsx [hunk 2]
```diff
@@ -21,6 +21,13 @@ export interface BaseDatePickerProps extends OutterCalendarProps {
    * @default Date(2100-01-01)
    */
   maxDate?: ParsableDate;
+
+  /**
+   * Compare date isBefore or isAfter without utils endOfDay or startOfDay
+   * @default false
+   */
+  validateStrict?: boolean;
```
Comment (dmtrKovalenko) [inline lib/src/DatePicker/DatePicker.tsx]: I suppose it must be named like `strictCompareDates`

**Comment by dmtrKovalenko** [comment]
And also needs to add some tests
