### PR TITLE
[typescript] Generic date type

### LINKED ISSUE #1861: TypeScript error  with v4.0.0-alpha.10
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    next     |
| material-ui          |   latest      |
| TypeScript           |  latest       |
| React                |    latest     |
| Peer library         |    dayjs latest     |  |

## Steps to reproduce

https://codesandbox.io/s/recursing-engelbart-wy2ub?file=/src/App.tsx

## Expected behavior

No error

## Actual behavior

```typescript
(JSX attribute) BasePickerProps<unknown, unknown>.onChange: (date: unknown, keyboardInputValue?: string | undefined) => void
onChange callback @DateIOType.

Type '(date: dayjs.Dayjs | null, keyboardInputValue?: string | undefined) => void' is not assignable to type '(date: unknown, keyboardInputValue?: string | undefined) => void'.
  Types of parameters 'date' and 'date' are incompatible.
    Type 'unknown' is not assignable to type 'Dayjs | null'.
      Type 'unknown' is not assignable to type 'Dayjs'.ts(2322)
```

Its left to fix this comment: https://github.com/mui-org/material-ui-pickers/issues/1861#issuecomment-658541026

### LINKED ISSUE #1881: Date control not working after adding aria-label with v4.0.0-alpha.8
Date control not working after adding aria-label, here is code -

```
<DateRangePicker
        value={selectedDate}
        onChange={handleDateChange}
        renderInput={(props1, props2) => {
          console.log("props1", props1);
          return (
            <React.Fragment>
              <TextField
                {...props1}
                variant="standard"
                aria-label="Start Date"
                inputProps={{ "aria-label": "Start Date" }}
              />
              <span>- </span>
              <TextField
                {...props2}
                variant="standard"
                aria-label="End Date"
                inputProps={{ "aria-label": "End Date" }}
              />
            </React.Fragment>
          );
        }}
      />
```
CodeSandbox to reproduce the issue
https://codesandbox.io/s/hungry-euclid-mgod9?file=/src/App.jsx

### LINKED ISSUE #1886: date-fns (DateFnsUtils ) type error on 4.0.0-alpha.8
A GIF or MEME to give some spice of the internet

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.8     |
| material-ui          |    4.10.2     |
| TypeScript           |    3.8.3     |
| React                |    16.13.1     |
| Browser              |    Chrome 83.0.4103.97     |
| Peer library         |    date-fns 2.14.0     |  |

## Steps to reproduce

1. Try to use `<LocalizationProvider>` with `DateFnsUtils` from `@material-ui/pickers/adapter/date-fns`

## Expected behavior

LocalizationProvider dateAdapter prop accepts DateFnsUtils

## Actual behavior

LocalizationProvider dateAdapter does not accept DateFnsUtils

```
Type 'typeof DateFnsUtils' is not assignable to type 'new (...args: any) => MuiPickersAdapter'.
  Type 'DateFnsUtils' is missing the following properties from type 'IUtils<MaterialUiPickersDate>': yearFormat, yearMonthFormat, dateTime12hFormat, dateTime24hFormat, and 12 more.  TS2322

    36 |           }}
    37 |         >
  > 38 |           <LocalizationProvider dateAdapter={DateFnsUtils}>
       |                                 ^
    39 |             <CssBaseline />
    40 |             <ThemeProvider theme={theme}>{props.children}</ThemeProvider>
    41 |           </LocalizationProvider>
```

### LINKED ISSUE #1962: [RFC] Replace MaterialUiPickersDate type with DateType
Looking at the codebase, I believe we could gain in clarity by

- re-exporting `DateType` from `@date-io/type` so we can do `import { DateType } from '@material-ui/pickers'`
- replace `MaterialUiPickersDate` with `DateType | null` everywhere in the codebase

This discussion first started in https://github.com/mui-org/material-ui-pickers/pull/1955#discussion_r449787734.

Also, I have noticed a couple of places where `| null` seems redundant, for instance:

https://github.com/mui-org/material-ui-pickers/blob/8f895d5e438dcc8f7f04837763979a3009d777dc/lib/src/views/Calendar/useCalendarState.tsx#L11

For reference:

https://github.com/mui-org/material-ui-pickers/blob/8f895d5e438dcc8f7f04837763979a3009d777dc/lib/src/typings/date.ts#L1-L3

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).

This PR closes #1861 , and also closes #1962

## User facing changes 

All exported pickers components are generics from now. It means that it will try to infer the `value` and `onChange(date: ?)` type from the passed value. In order to get rid of `@date-io/type` and exported `MaterialUIPickersDate` which doesn't work starting from ts 3.9.

## Internal changes 

From now on actually all the internal props/arguments/variables that contain date value coming from date-io is handling as `unknown`. It is too hard and too verbose trying to make **literally  all** the components generic. So basically using `unknown` type as a nice alternative, because we really don't know which type is coming from the user.

### CODE REVIEW

File: lib/src/DateRangePicker/DateRangePickerInput.tsx [hunk 1]
```diff
@@ -1,9 +1,9 @@
 import * as React from 'react';
 import * as PropTypes from 'prop-types';
+
```
Comment (oliviertassinari) [inline lib/src/DateRangePicker/DateRangePickerInput.tsx]:
```suggestion
```

File: lib/src/DateRangePicker/DateRangePickerView.tsx [hunk 2]
```diff
@@ -1,7 +1,7 @@
 import * as React from 'react';
 import * as PropTypes from 'prop-types';
+
```
Comment (oliviertassinari) [inline lib/src/DateRangePicker/DateRangePickerView.tsx]:
```suggestion
```

File: lib/src/DateRangePicker/DateRangePickerViewDesktop.tsx [hunk 3]
```diff
@@ -1,9 +1,9 @@
 import * as React from 'react';
 import { DateRange } from './RangeTypes';
+
```
Comment (oliviertassinari) [inline lib/src/DateRangePicker/DateRangePickerViewDesktop.tsx]:
```suggestion
```

File: lib/src/DateRangePicker/DateRangePickerViewMobile.tsx [hunk 4]
```diff
@@ -1,9 +1,9 @@
 import * as React from 'react';
 import CalendarHeader from '../views/Calendar/CalendarHeader';
 import { DateRange } from './RangeTypes';
+
```
Comment (oliviertassinari) [inline lib/src/DateRangePicker/DateRangePickerViewMobile.tsx]:
```suggestion
```

File: lib/src/DateTimePicker/DateTimePickerToolbar.tsx [hunk 5]
```diff
@@ -3,10 +3,10 @@ import ToolbarText from '../_shared/ToolbarText';
 import PickerToolbar from '../_shared/PickerToolbar';
 import ToolbarButton from '../_shared/ToolbarButton';
 import DateTimePickerTabs from './DateTimePickerTabs';
+
```
Comment (oliviertassinari) [inline lib/src/DateTimePicker/DateTimePickerToolbar.tsx]:
```suggestion
```

File: lib/src/Picker/Picker.tsx [hunk 6]
```diff
@@ -1,12 +1,11 @@
 import * as React from 'react';
 import clsx from 'clsx';
+
```
Comment (oliviertassinari) [inline lib/src/Picker/Picker.tsx]:
```suggestion
```

File: lib/src/Picker/makePickerWithState.tsx [hunk 7]
```diff
@@ -1,7 +1,7 @@
 import * as React from 'react';
 import Picker, { ExportedPickerProps } from './Picker';
+
```
Comment (oliviertassinari) [inline lib/src/Picker/makePickerWithState.tsx]:
```suggestion
```

File: lib/src/__tests__/test-utils.tsx [hunk 8]
```diff
@@ -67,7 +66,7 @@ const getUtilClass = () => {
 };
 
 export const UtilClassToUse: any = getUtilClass();
-export const utilsToUse: IUtils<MaterialUiPickersDate> = new UtilClassToUse();
+export const utilsToUse: IUtils<any> = new UtilClassToUse();
```
Comment (oliviertassinari) [inline lib/src/__tests__/test-utils.tsx:69]: A side note, I believe it's a date adapter now, the name changed (not a util class)

File: lib/src/__tests__/typescript/GenericValues.tstest.tsx [hunk 9]
```diff
@@ -0,0 +1,79 @@
...
+// Also works for DateRangePicker
+<DateRangePicker<DateTime>
+  value={[new DateTime(), new DateTime()]}
+  onChange={date => date[0]?.set({ second: 15 })}
+  renderInput={props => <TextField {...props} />}
+/>;
+
+// Throws error if passed value is invalid
+<DatePicker<Date>
+  // @ts-expect-error Value is invalid
```
Comment (oliviertassinari) [inline lib/src/__tests__/typescript/GenericValues.tstest.tsx:26]: Cool, same tool as https://github.com/mui-org/material-ui/pull/21308 :)

File: lib/src/__tests__/typescript/GenericValues.tstest.tsx [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+    />
+  );
+};
+
+// Infer value type from the dateAdapter
+<DatePicker
+  value={new DateTime()}
+  onChange={date => console.log(date)}
+  renderInput={props => <TextField {...props} />}
+  dateAdapter={new LuxonAdapter()}
```
Comment (oliviertassinari) [inline lib/src/__tests__/typescript/GenericValues.tstest.tsx:50]: From what I understand, the prop will almost never be used. I believe people will use the `LocalizationProvider` in +90% of the use cases. I don't think that we need to test it.

I also think that we should move toward removing this prop, starting by hiding it and seeing the feedback we get. I will open an RFC for it.

File: lib/src/views/Calendar/CalendarHeader.tsx [hunk 11]
```diff
@@ -8,7 +8,7 @@ import { DatePickerView } from '../../DatePicker';
 import { SlideDirection } from './SlideTransition';
 import { makeStyles } from '@material-ui/core/styles';
 import { useUtils } from '../../_shared/hooks/useUtils';
-import { MaterialUiPickersDate } from '../../typings/date';
+
```
Comment (oliviertassinari) [inline lib/src/views/Calendar/CalendarHeader.tsx]:
```suggestion
```

File: lib/src/views/Calendar/Day.tsx [hunk 12]
```diff
@@ -5,7 +5,7 @@ import ButtonBase, { ButtonBaseProps } from '@material-ui/core/ButtonBase';
 import { ExtendMui } from '../../typings/helpers';
 import { onSpaceOrEnter } from '../../_helpers/utils';
 import { useUtils } from '../../_shared/hooks/useUtils';
-import { MaterialUiPickersDate } from '../../typings/date';
+
```
Comment (oliviertassinari) [inline lib/src/views/Calendar/Day.tsx]:
```suggestion
```

File: lib/src/views/Calendar/MonthSelection.tsx [hunk 13]
```diff
@@ -3,17 +3,17 @@ import Month from './Month';
 import { makeStyles } from '@material-ui/core/styles';
 import { useUtils } from '../../_shared/hooks/useUtils';
 import { ParsableDate } from '../../constants/prop-types';
-import { MaterialUiPickersDate } from '../../typings/date';
+
```
Comment (oliviertassinari) [inline lib/src/views/Calendar/MonthSelection.tsx]:
```suggestion
```

File: lib/src/views/Calendar/YearSelection.tsx [hunk 14]
```diff
@@ -1,6 +1,6 @@
 import * as React from 'react';
 import Year from './Year';
-import { MaterialUiPickersDate } from '../../typings/date';
+
```
Comment (oliviertassinari) [inline lib/src/views/Calendar/YearSelection.tsx]:
```suggestion
```

File: lib/src/views/Calendar/useCalendarState.tsx [hunk 15]
```diff
@@ -2,21 +2,21 @@ import * as React from 'react';
 import { CalendarViewProps } from './CalendarView';
 import { SlideDirection } from './SlideTransition';
 import { validateDate } from '../../_helpers/date-utils';
-import { MaterialUiPickersDate } from '../../typings/date';
+
```
Comment (oliviertassinari) [inline lib/src/views/Calendar/useCalendarState.tsx]:
```suggestion
```

**Review by oliviertassinari — COMMENTED** [review]
The tests look solid :)

**Comment by dmtrKovalenko** [comment]
Sorry for missing new lines @oliviertassinari, thanks for creating suggestions. I`ve been sure that it should be fixed by prettier or eslint

**Review by oliviertassinari — APPROVED** [review]

File: docs/layout/components/navigationMap.ts [hunk 16]
```diff
@@ -39,6 +39,7 @@ export const navItems = [
   {
     title: 'Guides',
     children: [
+      { title: 'Typescript', href: '/guides/typescript' },
```
Comment (oliviertassinari) [inline docs/layout/components/navigationMap.ts]:
```suggestion
      { title: 'TypeScript', href: '/guides/typescript' },
```

File: docs/pages/guides/typescript.mdx [hunk 17]
```diff
@@ -0,0 +1,83 @@
+import PageMeta from '_shared/PageMeta';
+
+<PageMeta
+  title="Typescript – @material-ui/pickers"
+  description="A guide of how to use @material-ui/pickers with typescript"
+/>
+
+## Typescript guide
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx]: As far as I know, these capitalizations are not correct: "Typescript", "typescript", the only valid one is "TypeScript": http://typescriptlang.org/.

```suggestion
## TypeScript guide
```

Comment (oliviertassinari) [reply docs/pages/guides/typescript.mdx]: cc @dtassone I have seen the same in the data grid.

File: docs/pages/guides/typescript.mdx [hunk 18]
```diff
@@ -0,0 +1,83 @@
+import PageMeta from '_shared/PageMeta';
+
+<PageMeta
+  title="Typescript – @material-ui/pickers"
+  description="A guide of how to use @material-ui/pickers with typescript"
+/>
+
+## TypeScript guide
+
+Pickers are originally written in typescript, so type definetions are provided with the code without any additional requirements.
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx]: It don't see the link between written in TypeScript and not required additional requirement. What about:

```suggestion
The date picker components come with built-in TypeScript definitions.
```

File: docs/pages/guides/typescript.mdx [hunk 19]
```diff
@@ -0,0 +1,83 @@
...
+Here is some information about how to achive better experience with typescript.
+
+<!-- https://stackoverflow.com/questions/62452160/material-datetimepicker-onchange-typescript-mismatch-error/62471345 -->
+
+#### Nullable value
+
+Any picker can return null in the `onChange` argument so if you are using `React.useState`, you **must** manually cast your default value as nullable. (e.g. `Date | null`)
+
+```tsx
+const MyComponent = () => {
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx]:
```suggestion
function MyComponent() {
```

File: docs/pages/guides/typescript.mdx [hunk 20]
```diff
@@ -0,0 +1,83 @@
...
+  const [date, setDate] = React.useState<Date | null>(new Date());
+
+  return (
+    <DatePicker
+      value={date}
+      onChange={date => setDate(date)}
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx]: It might be best to avoid the implicit returned value, I have already been leaning toward it to ease refactorization, but it doesn't make a huge different

```suggestion
      onChange={date => { setDate(date) }}
```

File: docs/pages/guides/typescript.mdx [hunk 21]
```diff
@@ -0,0 +1,83 @@
...
+
+<!-- https://stackoverflow.com/questions/62452160/material-datetimepicker-onchange-typescript-mismatch-error/62471345 -->
+
+#### Nullable value
+
+Any picker can return null in the `onChange` argument so if you are using `React.useState`, you **must** manually cast your default value as nullable. (e.g. `Date | null`)
+
+```tsx
+const MyComponent = () => {
+  const [date, setDate] = React.useState<Date | null>(new Date());
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx]: Assuming we don't know what the value will be used for, might be best to keep it generic?

```suggestion
  const [value, setValue] = React.useState<Date | null>(new Date());
```

File: docs/pages/guides/typescript.mdx [hunk 22]
```diff
@@ -0,0 +1,83 @@
...
+/>
+
+## TypeScript guide
+
+Pickers are originally written in typescript, so type definetions are provided with the code without any additional requirements.
+Here is some information about how to achive better experience with typescript.
+
+<!-- https://stackoverflow.com/questions/62452160/material-datetimepicker-onchange-typescript-mismatch-error/62471345 -->
+
+#### Nullable value
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx:15]: The heading structure needs to be linear h1 > h2 > h3, jumps are not allowed

```suggestion
### Nullable value
```

File: docs/pages/guides/typescript.mdx [hunk 23]
```diff
@@ -0,0 +1,83 @@
+import PageMeta from '_shared/PageMeta';
+
+<PageMeta
+  title="Typescript – @material-ui/pickers"
+  description="A guide of how to use @material-ui/pickers with typescript"
+/>
+
+## TypeScript guide
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx:8]:
```suggestion
# TypeScript guide
```

Comment (dmtrKovalenko) [reply docs/pages/guides/typescript.mdx:8]: Ohhh no no no, our styling is really weird if using right h1, h2 :) 

Needs to be fixed or wait for migration

File: docs/pages/guides/typescript.mdx [hunk 24]
```diff
@@ -0,0 +1,83 @@
...
+      onChange={date => setDate(date)}
+      renderInput={props => <TextField {...props} />}
+    />
+  );
+};
+```
+
+#### Generics
+
+We don't really know which adapter you will pass to the `<LocalizationProvider />`. So any picker component is generic by default.
```
Comment (oliviertassinari) [inline docs/pages/guides/typescript.mdx]: Please remove all usage of "we" for "it" when mentioning how the code behaves.
```suggestion
The components don't know which adapter you will pass to the `<LocalizationProvider />`. So any picker component is generic by default.
```

File: docs/pages/guides/typescript.mdx (hunk 23 above)
Comment (oliviertassinari) [reply docs/pages/guides/typescript.mdx:8]: Ok, let's wait migration :)

File: docs/pages/guides/typescript.mdx (hunk 24 above)
Comment (oliviertassinari) [reply docs/pages/guides/typescript.mdx]: cc @mbrookes has this guideline come from him

File: lib/src/__tests__/typescript/GenericValues.tstest.tsx [hunk 25]
```diff
@@ -0,0 +1,79 @@
+/* eslint-disable @typescript-eslint/no-unused-vars */
+import * as React from 'react';
```
Comment (oliviertassinari) [inline lib/src/__tests__/typescript/GenericValues.tstest.tsx:2]: One question, how are these tests run in the CI (`*.tstest.tsx` files)? I can't find where it comes from. Is it just by using the same prefix?
